#!/usr/bin/env bash
# DistroForge Installer
#
# Usage (one-liner):
#   bash <(curl -fsSL https://raw.githubusercontent.com/rezalabshq/DistroForge/main/install.sh)
#
# Or clone first:
#   git clone https://github.com/rezalabshq/DistroForge.git && bash DistroForge/install.sh

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/rezalabshq/DistroForge.git"
APP_NAME="distroforge"
INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/${APP_NAME}"
BIN_DIR="${HOME}/.local/bin"
VENV_DIR="${INSTALL_DIR}/.venv"
MIN_PYTHON_MINOR=10

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

ok()   { echo -e " ${GREEN}✓${NC}  $*"; }
info() { echo -e " ${CYAN}→${NC}  $*"; }
warn() { echo -e " ${YELLOW}⚠${NC}  $*"; }
die()  { echo -e " ${RED}✗${NC}  $*" >&2; exit 1; }

# ── Header ────────────────────────────────────────────────────────────────────
echo
echo -e "${CYAN}${BOLD}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║     DistroForge — Installer          ║${NC}"
echo -e "${CYAN}${BOLD}╚══════════════════════════════════════╝${NC}"
echo -e "${DIM}  by Hamid at Reza Labs HQ${NC}"
echo

# ── Requirements ──────────────────────────────────────────────────────────────
info "Checking requirements..."

# git
command -v git &>/dev/null || die "git is required. Install it: sudo apt install git"
ok "git $(git --version | awk '{print $3}')"

# Python 3.10+
PYTHON_CMD=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        minor=$("$cmd" -c "import sys; print(sys.version_info.minor)")
        major=$("$cmd" -c "import sys; print(sys.version_info.major)")
        if [[ "$major" -eq 3 && "$minor" -ge "$MIN_PYTHON_MINOR" ]]; then
            PYTHON_CMD="$cmd"
            break
        fi
    fi
done
[[ -n "$PYTHON_CMD" ]] || die "Python 3.${MIN_PYTHON_MINOR}+ is required. Install it: sudo apt install python3"
ok "Python $("$PYTHON_CMD" --version 2>&1 | awk '{print $2}')"

# ── Install / Update ──────────────────────────────────────────────────────────
echo
if [[ -d "${INSTALL_DIR}/.git" ]]; then
    info "Updating existing installation at ${INSTALL_DIR}..."
    git -C "$INSTALL_DIR" pull --ff-only --quiet
    ok "Updated to latest"
else
    info "Cloning DistroForge to ${INSTALL_DIR}..."
    mkdir -p "$(dirname "$INSTALL_DIR")"
    git clone --depth 1 --quiet "$REPO_URL" "$INSTALL_DIR"
    ok "Cloned successfully"
fi

# ── Python Environment ────────────────────────────────────────────────────────
echo
info "Setting up Python environment..."

if [[ ! -d "$VENV_DIR" ]]; then
    "$PYTHON_CMD" -m venv "$VENV_DIR"
fi

"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet -r "${INSTALL_DIR}/requirements.txt"
ok "Dependencies installed (rich, pyyaml)"

# ── Launcher Script ───────────────────────────────────────────────────────────
echo
info "Creating launcher at ${BIN_DIR}/${APP_NAME}..."
mkdir -p "$BIN_DIR"

cat > "${BIN_DIR}/${APP_NAME}" <<EOF
#!/usr/bin/env bash
# DistroForge launcher — generated by install.sh
exec "${VENV_DIR}/bin/python" "${INSTALL_DIR}/distroforge.py" "\$@"
EOF

chmod +x "${BIN_DIR}/${APP_NAME}"
ok "Launcher created"

# ── PATH check ────────────────────────────────────────────────────────────────
echo
SHELL_RC=""
if [[ -f "$HOME/.zshrc" ]]; then
    SHELL_RC="$HOME/.zshrc"
elif [[ -f "$HOME/.bashrc" ]]; then
    SHELL_RC="$HOME/.bashrc"
fi

PATH_LINE='export PATH="$HOME/.local/bin:$PATH"'

if [[ ":$PATH:" != *":${BIN_DIR}:"* ]]; then
    warn "${BIN_DIR} is not in your current PATH"
    if [[ -n "$SHELL_RC" ]]; then
        if ! grep -qF "$PATH_LINE" "$SHELL_RC" 2>/dev/null; then
            echo "" >> "$SHELL_RC"
            echo "# Added by DistroForge installer" >> "$SHELL_RC"
            echo "$PATH_LINE" >> "$SHELL_RC"
            ok "Added ${BIN_DIR} to ${SHELL_RC}"
            export PATH="$HOME/.local/bin:$PATH"
        fi
    else
        echo
        echo -e "  Add this to your shell config:"
        echo -e "  ${CYAN}${PATH_LINE}${NC}"
        echo
    fi
else
    ok "${BIN_DIR} is already in PATH"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo
echo -e "${GREEN}${BOLD}DistroForge installed successfully!${NC}"
echo
echo -e "  ${BOLD}Usage:${NC}"
echo -e "    ${CYAN}distroforge${NC}                      — interactive mode"
echo -e "    ${CYAN}distroforge --list${NC}               — show available phases"
echo -e "    ${CYAN}distroforge --phases verify${NC}      — run health check"
echo -e "    ${CYAN}distroforge --dry-run --yes${NC}      — preview all phases"
echo -e "    ${CYAN}distroforge --phases system,shell${NC} — run specific phases"
echo
echo -e "  ${BOLD}Config:${NC}  ${INSTALL_DIR}/config.yaml"
echo -e "  ${BOLD}Logs:${NC}    ~/.distroforge/logs/"
echo -e "  ${BOLD}Update:${NC}  bash ${INSTALL_DIR}/install.sh"
echo
echo -e "  ${DIM}Reload your shell or run: source ${SHELL_RC:-~/.bashrc}${NC}"
echo
