#!/usr/bin/env bash
# DistroForge installer — per-user, no root required.
#
#   bash <(curl -fsSL https://raw.githubusercontent.com/RezaLabsHQ/DistroForge/main/install.sh)
#
# or from a checkout:   ./install.sh
#
# What it does:
#   1. installs the `distroforge` command with pipx, or into a private venv
#      at ~/.local/share/distroforge/venv with a launcher in ~/.local/bin
#   2. runs `distroforge integrate`: app-menu entry (opens in your terminal),
#      icon, and bash/zsh/fish completions
#
# Environment overrides:
#   DISTROFORGE_SOURCE   pip-installable source (path, URL or git+https URL)
#   DISTROFORGE_REF      git ref to install when downloading (default: main)
#   DISTROFORGE_NO_PIPX  set to 1 to force the venv method
set -euo pipefail

APP="distroforge"
REPO="https://github.com/RezaLabsHQ/DistroForge"
REF="${DISTROFORGE_REF:-main}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
APP_DIR="$DATA_HOME/$APP"
VENV="$APP_DIR/venv"
BIN_DIR="$HOME/.local/bin"
MIN_MINOR=10

if [[ -t 1 ]]; then
    B=$'\033[1m' D=$'\033[2m' R=$'\033[31m' G=$'\033[32m' Y=$'\033[33m' C=$'\033[36m' N=$'\033[0m'
else
    B="" D="" R="" G="" Y="" C="" N=""
fi
ok()   { printf ' %s✓%s %s\n' "$G" "$N" "$*"; }
info() { printf ' %s→%s %s\n' "$C" "$N" "$*"; }
warn() { printf ' %s⚠%s %s\n' "$Y" "$N" "$*"; }
die()  { printf ' %s✗%s %s\n' "$R" "$N" "$*" >&2; exit 1; }

printf '\n%s  ✦ DistroForge installer%s\n%s  forge your Linux setup%s\n\n' "$B$C" "$N" "$D" "$N"

[[ "$(uname -s)" == "Linux" ]] || die "DistroForge runs on Linux only."
[[ "$EUID" -ne 0 ]] || die "Run this as your normal user, not root. DistroForge uses sudo only when needed."

# ── Python ────────────────────────────────────────────────────────────────────
PYTHON=""
for candidate in python3 python; do
    if command -v "$candidate" >/dev/null 2>&1 &&
        "$candidate" -c "import sys; sys.exit(0 if sys.version_info >= (3, $MIN_MINOR) else 1)" 2>/dev/null; then
        PYTHON="$(command -v "$candidate")"
        break
    fi
done
[[ -n "$PYTHON" ]] || die "Python 3.$MIN_MINOR+ is required. Install it with your package manager (python3)."
ok "Python $("$PYTHON" -c 'import platform; print(platform.python_version())')"

# ── Source ────────────────────────────────────────────────────────────────────
SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi
if [[ -n "${DISTROFORGE_SOURCE:-}" ]]; then
    SOURCE="$DISTROFORGE_SOURCE"
elif [[ -n "$SCRIPT_DIR" && -f "$SCRIPT_DIR/pyproject.toml" && -d "$SCRIPT_DIR/src/distroforge" ]]; then
    SOURCE="$SCRIPT_DIR"
else
    SOURCE="$REPO/archive/$REF.tar.gz"
fi
info "Installing from $SOURCE"

# ── Migrate a 1.x install (git clone + hand-written launcher) ─────────────────
if [[ -d "$APP_DIR/.git" && -f "$APP_DIR/distroforge.py" ]]; then
    warn "Found DistroForge 1.x in $APP_DIR — replacing it"
    rm -rf -- "${APP_DIR:?}"
    if [[ -f "$BIN_DIR/$APP" ]] && grep -q "generated by install.sh" "$BIN_DIR/$APP" 2>/dev/null; then
        rm -f -- "$BIN_DIR/$APP"
    fi
    ok "Removed 1.x files (your old config.local.yaml is no longer used; see 'distroforge profiles')"
fi

# ── Install ───────────────────────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
METHOD=""
if [[ "${DISTROFORGE_NO_PIPX:-0}" != "1" ]] && command -v pipx >/dev/null 2>&1; then
    info "Using pipx"
    pipx install --force "$SOURCE" >/dev/null
    METHOD="pipx"
    EXE="$(command -v "$APP" || true)"
    [[ -n "$EXE" ]] || EXE="$BIN_DIR/$APP"
else
    if ! "$PYTHON" -c "import venv, ensurepip" 2>/dev/null; then
        die "Python's venv module is missing. Install it first, e.g.: sudo apt install python3-venv"
    fi
    info "Creating a private environment in $VENV"
    mkdir -p "$APP_DIR"
    if [[ ! -x "$VENV/bin/python" ]]; then
        "$PYTHON" -m venv "$VENV"
    fi
    "$VENV/bin/python" -m pip install --quiet --upgrade pip
    "$VENV/bin/python" -m pip install --quiet --upgrade "$SOURCE"
    ln -sf "$VENV/bin/$APP" "$BIN_DIR/$APP"
    METHOD="venv"
    EXE="$BIN_DIR/$APP"
fi
VERSION="$("$EXE" --version 2>/dev/null | awk '{print $2}')"
[[ -n "$VERSION" ]] || die "Installation finished but '$EXE' does not run."
ok "Installed DistroForge $VERSION ($METHOD)"
printf '%s\n' "$METHOD" > "$APP_DIR/install-method" 2>/dev/null || { mkdir -p "$APP_DIR" && printf '%s\n' "$METHOD" > "$APP_DIR/install-method"; }

# ── Desktop integration ───────────────────────────────────────────────────────
if "$EXE" integrate --exec "$EXE" >/dev/null; then
    ok "Added to your app menu (opens in your terminal), with icon and shell completions"
else
    warn "Could not add the app-menu entry — run '$APP integrate' later"
fi

# ── PATH ──────────────────────────────────────────────────────────────────────
case ":$PATH:" in
    *":$BIN_DIR:"*) ok "$BIN_DIR is on your PATH" ;;
    *)
        warn "$BIN_DIR is not on your PATH yet"
        printf '   Add this to your shell startup file, then open a new terminal:\n'
        # shellcheck disable=SC2016  # printed literally for the user to copy
        printf '   %sexport PATH="$HOME/.local/bin:$PATH"%s\n' "$C" "$N"
        ;;
esac

cat <<EOF

${G}${B}DistroForge is ready.${N}

  ${B}distroforge${N}                      open the app (or find "DistroForge" in your menu)
  ${B}distroforge apply --profile essentials --dry-run${N}
  ${B}distroforge doctor${N}               check detection and setup
  ${B}distroforge --help${N}

  Uninstall:  ${D}bash $APP_DIR/uninstall.sh${N}  ${D}(or ./uninstall.sh from the repo)${N}

EOF

# Keep a copy of the uninstaller next to the install.
if [[ -n "$SCRIPT_DIR" && -f "$SCRIPT_DIR/uninstall.sh" ]]; then
    install -m 0755 "$SCRIPT_DIR/uninstall.sh" "$APP_DIR/uninstall.sh"
elif command -v curl >/dev/null 2>&1; then
    curl -fsSL "https://raw.githubusercontent.com/RezaLabsHQ/DistroForge/$REF/uninstall.sh" -o "$APP_DIR/uninstall.sh" &&
        chmod 0755 "$APP_DIR/uninstall.sh" || true
fi
